// <auto-generated />
using System;
using CRUD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD.Migrations
{
    [DbContext(typeof(eCommerceContext))]
    [Migration("20250731151350_started")]
    partial class started
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUD.Models.Category", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("catname")
                        .IsRequired()
                        .HasColumnType("Varchar(50)")
                        .HasColumnName("CategoryName");

                    b.HasKey("id");

                    b.ToTable("tbl_categories");
                });

            modelBuilder.Entity("CRUD.Models.Product", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("Varchar(220)")
                        .HasColumnName("ProductDescription");

                    b.Property<string>("image")
                        .HasColumnType("Varchar(220)")
                        .HasColumnName("ProductImage");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("Varchar(120)")
                        .HasColumnName("ProductName");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal")
                        .HasColumnName("ProductPrice");

                    b.Property<int>("stock")
                        .HasColumnType("int")
                        .HasColumnName("ProductStock");

                    b.HasKey("id");

                    b.HasIndex("CategoryId");

                    b.ToTable("tbl_products");
                });

            modelBuilder.Entity("CRUD.Models.Product", b =>
                {
                    b.HasOne("CRUD.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
